name: travel-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  # Base dependencies
  - aiohttp>=3.9.0
  - pydantic>=2.5.0
  - python-dotenv>=1.0.0
  - requests>=2.31.0
  - pandas>=2.1.0
  - numpy>=1.24.0
  - altair
  # Development dependencies
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - pytest-asyncio>=0.21.0
  - pytest-mock>=3.12.0
  - black>=23.10.0
  - flake8>=6.1.0
  - isort>=5.12.0
  - mypy>=1.7.0
  - ipython>=8.17.0
  - jupyter>=1.0.0
  # Production dependencies
  - gunicorn>=21.2.0
  - pip:
    - streamlit
    - streamlit-extras
    - streamlit-option-menu
    - streamlit-calendar
    - streamlit-aggrid
    - streamlit-elements
    - plotly
    - sentry-sdk>=1.32.0
    - newrelic>=9.0.0
    - prometheus-client>=0.18.0
